"""
UTILITY: Index Persistence & Disk Offloading
--------------------------------------------
PURPOSE:
Handles the 'Index Creation' phase by persisting the in-memory inverted index
to the local file system. This module provides the interface for offloading
partial indexes to prevent memory overflow during the 56k document run.

TECHNICAL SPECIFICATIONS:
- Format: Serializes the dictionary into binary format using 'pickle'.
- Optimization: Alphabetically sorts tokens (keys) before saving. This
  is a critical design choice to allow for an efficient O(N) linear
  K-Way Merge in Milestone 2.
- Persistence: Writes data to the 'index_batches' directory as .bin files.

TEAM NOTES (Alexander & Kenny):
- Every .bin file generated by this module is pre-sorted by token.
- Do not modify the sorting logic without coordinating, as the future
  merger relies on this deterministic order.
"""

import pickle

def save_index_to_disk(index_to_save, filename):
    #save inverted index to a binary file because its faster than json

    #sort by token because needed for later merge
    sorted_index = dict(sorted(index_to_save.items()))

    with open(filename, 'wb') as f:
        pickle.dump(sorted_index, f)
    print(f"Index saved to {filename}")